// Code generated by protoc-gen-go.
// source: protos/golang.yacloud.eu/apis/session/session.proto
// DO NOT EDIT!

/*
Package session is a generated protocol buffer package.

It is generated from these files:
	protos/golang.yacloud.eu/apis/session/session.proto

It has these top-level messages:
	Organisation
	Session
*/
package session

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Organisation struct {
	ID           string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	FriendlyName string `protobuf:"bytes,2,opt,name=FriendlyName" json:"FriendlyName,omitempty"`
}

func (m *Organisation) Reset()                    { *m = Organisation{} }
func (m *Organisation) String() string            { return proto.CompactTextString(m) }
func (*Organisation) ProtoMessage()               {}
func (*Organisation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Organisation) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Organisation) GetFriendlyName() string {
	if m != nil {
		return m.FriendlyName
	}
	return ""
}

type Session struct {
	SessionID    string        `protobuf:"bytes,1,opt,name=SessionID" json:"SessionID,omitempty"`
	Organisation *Organisation `protobuf:"bytes,2,opt,name=Organisation" json:"Organisation,omitempty"`
	UserID       string        `protobuf:"bytes,3,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Session) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *Session) GetOrganisation() *Organisation {
	if m != nil {
		return m.Organisation
	}
	return nil
}

func (m *Session) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func init() {
	proto.RegisterType((*Organisation)(nil), "session.Organisation")
	proto.RegisterType((*Session)(nil), "session.Session")
}

func init() {
	proto.RegisterFile("protos/golang.yacloud.eu/apis/session/session.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x32, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x4f, 0xcf, 0xcf, 0x49, 0xcc, 0x4b, 0xd7, 0xab, 0x4c, 0x4c, 0xce, 0xc9, 0x2f,
	0x4d, 0xd1, 0x4b, 0x2d, 0xd5, 0x4f, 0x2c, 0xc8, 0x2c, 0xd6, 0x2f, 0x4e, 0x2d, 0x2e, 0xce, 0xcc,
	0xcf, 0x83, 0xd1, 0x7a, 0x60, 0xd5, 0x42, 0xec, 0x50, 0xae, 0x92, 0x13, 0x17, 0x8f, 0x7f, 0x51,
	0x7a, 0x62, 0x5e, 0x66, 0x71, 0x62, 0x49, 0x66, 0x7e, 0x9e, 0x10, 0x1f, 0x17, 0x93, 0xa7, 0x8b,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x93, 0xa7, 0x8b, 0x90, 0x12, 0x17, 0x8f, 0x5b, 0x51,
	0x66, 0x6a, 0x5e, 0x4a, 0x4e, 0xa5, 0x5f, 0x62, 0x6e, 0xaa, 0x04, 0x13, 0x58, 0x06, 0x45, 0x4c,
	0xa9, 0x8a, 0x8b, 0x3d, 0x18, 0x62, 0x9c, 0x90, 0x0c, 0x17, 0x27, 0x94, 0x09, 0x37, 0x05, 0x21,
	0x20, 0x64, 0x89, 0x6a, 0x19, 0xd8, 0x30, 0x6e, 0x23, 0x51, 0x3d, 0x98, 0xdb, 0x90, 0x25, 0x83,
	0x50, 0xdd, 0x25, 0xc6, 0xc5, 0x16, 0x5a, 0x9c, 0x5a, 0xe4, 0xe9, 0x22, 0xc1, 0x0c, 0x36, 0x15,
	0xca, 0x73, 0xb2, 0xe4, 0x12, 0x4f, 0x2d, 0x85, 0x7b, 0x1a, 0xe4, 0x63, 0x98, 0x69, 0x51, 0x72,
	0xf8, 0x43, 0x24, 0x89, 0x0d, 0x1c, 0x14, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xb4,
	0xc2, 0xde, 0x41, 0x01, 0x00, 0x00,
}




